name: Terraform fmt check

on:
  push:

jobs:
  tf-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7
      - name: Terraform fmt
        run: terraform fmt -check -recursive
